[package]
name = "nola-playground-impl"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
nola-abi-playground = { path = "../nola-abi-playground" }
nola-playground-lib = { path = "../nola-playground-lib" }

[lib]
crate-type = ["cdylib"]
